/*
 * Copyright (c) 2017, Salesforce.com, Inc.
 * All rights reserved.
 */

package com.salesforce.op

import java.io.File

import com.salesforce.op.utils.json.{JsonLike, JsonUtils}

import scala.util.Try


/**
 * OpParams for passing in command line information
 *
 * @param stageParams     a map of parameters to inject into stages.
 *                        Format is Map(StageSimpleName -> Map(ParameterName -> Value)).
 *                        Allows changing parameters away from defaults (and only defaults) at the level of stage type
 *                        (all stages of the same type will get the same setting.
 *                        Note: Will NOT override parameter values that have been
 *                        set previously in code OR with a previous set of parameters.
 * @param readerParams    a map of parameters to inject into readers.
 *                        Format is Map(ReaderType -> Map(ParameterName -> Value)).
 *                        In order to use these parameters the read method in the reader must be overwritten to
 *                        specifically take and use these parameters.
 * @param modelLocation   location to save model to or read model from
 * @param writeLocation   location to write out any data generated by flow
 * @param metricsLocation location to write out any metrics generated by flow
 * @param metricsCompress should compress metrics file
 * @param metricsCodec    compress with the supplied codec
 * @param customTagName   tag name printed on log lines (e.g., by [[com.salesforce.op.utils.spark.OpSparkListener]])
 * @param customTagValue  the value for the tag printed on log lines
 *                        (e.g., by [[com.salesforce.op.utils.spark.OpSparkListener]])
 * @param logStageMetrics if [[com.salesforce.op.utils.spark.OpSparkListener]] should log metrics for every stage.
 *                        Note: can increase logging significantly if app has too many stages.
 * @param customParams    any custom parameters
 */
final class OpParams
(
  val stageParams: Map[String, Map[String, Any]],
  val readerParams: Map[String, ReaderParams],
  val modelLocation: Option[String],
  val writeLocation: Option[String],
  val metricsLocation: Option[String],
  val metricsCompress: Option[Boolean],
  val metricsCodec: Option[String],
  val customTagName: Option[String],
  val customTagValue: Option[String],
  val logStageMetrics: Option[Boolean],
  val customParams: Map[String, Any]
) extends JsonLike {

  // fix for jackson putting in nulls
  def this() = this(Map.empty, Map.empty, None, None, None, None, None, None, None, None, Map.empty)

  /**
   * Copy op params with new specified values
   *
   * @param readLocations   read locations
   * @param writeLocation   write locations
   * @param modelLocation   model location
   * @param metricsLocation metrics location
   * @return a copy of params with new values
   */
  def withValues(
    readLocations: Map[String, String] = Map.empty,
    writeLocation: Option[String] = None,
    modelLocation: Option[String] = None,
    metricsLocation: Option[String] = None
  ): OpParams = {
    val existingReadLocations = readerParams.collect { case (k, r) if r.path.isDefined => k -> r.path.get }
    val newReaderParams = (existingReadLocations ++ readLocations).map { case (k, v) =>
      if (readerParams.contains(k)) k -> readerParams(k).withValues(path = v)
      else k -> new ReaderParams(path = Option(v), partitions = None, customParams = Map.empty)
    }
    new OpParams(
      stageParams = stageParams,
      readerParams = newReaderParams,
      modelLocation = if (modelLocation.nonEmpty) modelLocation else this.modelLocation,
      writeLocation = if (writeLocation.nonEmpty) writeLocation else this.writeLocation,
      metricsLocation = if (metricsLocation.nonEmpty) metricsLocation else this.metricsLocation,
      metricsCompress = metricsCompress,
      metricsCodec = metricsCodec,
      customTagName = customTagName,
      customTagValue = customTagValue,
      logStageMetrics = logStageMetrics,
      customParams = customParams
    )
  }
}

/**
 * Reader params
 *
 * @param path         read path
 * @param partitions   if specified, will repartition
 * @param customParams any custom parameters
 */
final class ReaderParams
(
  val path: Option[String],
  val partitions: Option[Int],
  val customParams: Map[String, Any]
) extends JsonLike {

  def this() = this(None, None, Map.empty) // fix for jackson putting in nulls

  /**
   * Copy reader params with new values
   * @param path path
   * @return a copy of params with new values
   */
  def withValues(path: String): ReaderParams =
    new ReaderParams(
      path = Option(path),
      partitions = partitions,
      customParams = customParams
    )
}

/**
 * A helper object for OpParams marshalling
 */
object OpParams {

  /**
   * Read OpParams params from a json or yaml file
   *
   * @param paramsFile json or yaml file to read params from
   * @return Try[OpWorkflowParams]
   */
  def fromFile(paramsFile: File): Try[OpParams] = JsonUtils.fromFile[OpParams](paramsFile)

  /**
   * Read OpParams params from a json or yaml string
   *
   * @param paramsStr params string as a json or yaml
   * @return Try[OpWorkflowParams]
   */
  def fromString(paramsStr: String): Try[OpParams] = JsonUtils.fromString[OpParams](paramsStr)

  /**
   * Write params instance to yaml string
   *
   * @param params instance
   * @return yaml string of the instance
   */
  def toYamlString(params: OpParams): String = JsonUtils.toYamlString(params)

}
